###
# This file will run with VS Code REST Client Extension
#
# Environment Variables
# "API_BASE": API_ENDPOINT,
# "token": AUTH_TOKEN,
# "userId": USER_ID,
# "categoryId": CATEGORY_ID,
# "productId": PRODUCT_ID
#
####

### Sign Up
POST {{API_BASE}}/signup HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "password": "1234567890" 
}

### Sign Up 2
POST {{API_BASE}}/signup HTTP/1.1
Content-Type: application/json

{
  "name": "Sam Smith",
  "email": "sam@example.com",
  "password": "1234567890" 
}

### Sign In (Admin) Manually create admin by changing user role in DB to 1
POST {{API_BASE}}/signin HTTP/1.1
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "1234567890"
}


### Sign In 2 (Not Admin)
POST {{API_BASE}}/signin HTTP/1.1
Content-Type: application/json

{
  "email": "sam@example.com",
  "password": "1234567890"
}

### Get User
GET {{API_BASE}}/user/{{userId}} HTTP/1.1
Content-Type: application/json
Authorization : Bearer {{token}}

### Update User
PUT {{API_BASE}}/user/{{userId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John William Doe"
}

### Create Category
POST {{API_BASE}}/category/create/{{userId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Rainy"
}

### Update Category
PUT {{API_BASE}}/category/{{categoryId}}/{{userId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Rainy is awesome"
}

### Delete Category
DELETE  {{API_BASE}}/category/{{categoryId}}/{{userId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Rainy is awesome"
}


### Create Product
POST {{API_BASE}}/product/create/{{userId}} HTTP/1.1
Content-Type: multipart/form-data
Authorization: Bearer {{token}}

{
  "name": "I love code! T-Shirt",
  "description": "Classic T-Shirt",
  "price": "$10",
  "category": "5f2b1e773ad7a94f6c851cf8",
  "stock": 5,
  "photo": < ./tshirts/one.png,
}

### Braintree Generate Token
GET {{API_BASE}}/payment/getToken/{{userId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Braintree Process Payment
POST {{API_BASE}}/payment/braintree/{{userId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{	
  "paymentMethodNonce": "thisisweirdnonce",
  "amount": "200.00"
}