import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import { useCart, useUser } from '@store/index';
import Cart from '@components/user/cart';
import Details from '@components/user/cart/Details';

const Checkout: NextPage = () => {
  const { items, actions, amount } = useCart();
  const user = useUser();
  const isCartEmpty = items.length <= 0;

  if (!user) {
    return null;
  }

  return (
    <div className="flex-1">
      <Head>
        <title>Shopper Ave - Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto md:w-1/2">
        <section className="px-5 py-3">
          <Cart items={items} actions={actions} isCartEmpty={isCartEmpty} amount={amount} />
        </section>
        <section className="px-5 py-3">
          {user.addresses && (
            <Details addresses={user.addresses} defaultValue={user.addresses[0]} />
          )}
        </section>
      </div>
    </div>
  );
};

export default Checkout;
