import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import { useCart } from '@store/index';
import Cart from '@components/user/cart';

const Checkout: NextPage = () => {
  const { items, actions, amount } = useCart();
  const isCartEmpty = items.length <= 0;

  return (
    <div className="flex-1">
      <Head>
        <title>Shopper Ave - Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="mx-auto px-5 py-6 md:w-1/2">
        <Cart items={items} actions={actions} isCartEmpty={isCartEmpty} amount={amount} />
      </section>
    </div>
  );
};

export default Checkout;
