import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { loadStripe, StripeElementsOptions } from '@stripe/stripe-js';
import { Elements } from '@stripe/react-stripe-js';
import { MinusCircleIcon } from '@heroicons/react/24/outline';

import { useCart } from '@store/index';
import { capturePayment } from '@api/user';
import CheckoutForm from '@components/user/payment/CheckoutForm';

const stripePromise = loadStripe(process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY);

const Checkout: NextPage = () => {
  const { items, actions } = useCart();

  const appearance: StripeElementsOptions['appearance'] = {
    theme: 'stripe',
    labels: 'above',
  };

  return (
    <div>
      <Head>
        <title>Shopper Ave - Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col p-2 md:flex-row lg:p-5">
        <section className="w-1/2">
          <div className="mx-auto max-w-[500px] space-y-2 p-5">
            {items.map(({ _id, name, photos, quantity }) => (
              <div key={_id} className="flex items-center">
                <img
                  src={photos[0].secure_url}
                  alt={name}
                  className="h-[60px] w-[60px] rounded-lg object-cover"
                />
                <div className="ml-4 flex-1">
                  <h6 className="text-lg">{name}</h6>
                  <div>
                    <span className="italic">Quantity:</span>
                    <span className="ml-2">{quantity}</span>
                  </div>
                </div>
                <div>
                  <button onClick={() => actions.remove(_id)}>
                    <MinusCircleIcon className="h-6 w-6" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </section>
        <section className="w-1/2 px-8">
          <Elements options={{ appearance }} stripe={stripePromise}>
            <CheckoutForm />
          </Elements>
        </section>
      </div>
    </div>
  );
};

export default Checkout;
