import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { loadStripe, StripeElementsOptions } from '@stripe/stripe-js';
import { Elements } from '@stripe/react-stripe-js';

import CheckoutForm from '@components/user/payment/CheckoutForm';

const stripePromise = loadStripe(process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY);

const Checkout: NextPage = () => {
  const appearance: StripeElementsOptions['appearance'] = {
    theme: 'stripe',
    labels: 'above',
  };

  return (
    <div>
      <Head>
        <title>Shopper Ave - Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col p-2 md:flex-row lg:p-5">
        <section className="mx-auto px-8 lg:w-1/2">
          <Elements options={{ appearance }} stripe={stripePromise}>
            <CheckoutForm />
          </Elements>
        </section>
      </div>
    </div>
  );
};

export default Checkout;
