import type { NextPage } from 'next';
import Head from 'next/head';

const Collection: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Shopper Ave</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-center">Collection feature is not available as of now. Coming soon.</h1>
    </div>
  );
};

export default Collection;
