import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Shopper Ave</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid">
        <section>Banner</section>
        <section>Offer</section>
        <aside>Sidebar</aside>
        <section>Products</section>
      </main>
    </div>
  );
};

export default Home;
