import type { NextPage } from "next";
import Head from "next/head";

const SignUp: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Shopper Ave</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Shopper Ave</h1>
    </div>
  );
};

export default SignUp;
